### ISSUE TITLE
ubuntu 18.04 不能启动

### ISSUE THREAD

**Issue by pencil3mark** [richardxzh/qemustart#2]
系统信息：
`uname -a 
Linux ubuntu 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
故障1：
运行命令后，虚拟机无法启动，镜像为armhf。

![image](https://user-images.githubusercontent.com/21230348/146166368-1ee21b09-c9ff-4c4b-a83a-09ab26466de3.png)

解：
apt-get  install  qemu-system-arm

故障2：
虚拟机启动后，不能进入chroot环境：
![image](https://user-images.githubusercontent.com/21230348/146166663-6d3ae773-bdee-49d7-9853-b91e9b914f55.png)

解：
apt-get install net-tools
查看宿主ip，tap0 192.168.3.1 OK

**Comment by LittleRx** [comment]
Hi,  @pencil3mark  Thanks for your submit
I will improve this by the next version
- [x] perfect requirement 
- [x] Solve the problem that the network tool does not exist

**Comment by LittleRx** [comment]
I have finished this issue.
